@startuml
title Checkout Sequence
hide footbox
autoactivate on

actor "Browser" as client
participant "Spring Boot Framework" as SB
participant CustomerController
participant UserService
participant ShoppingCartController
participant DataStore
participant CheckOutController
participant CheckOutView



client -> SB : POST("/shop/checkout")

== Customer Interaction ==
SB -> CustomerController : getCurrentCustomer()
note left
Exact interaction between
Spring Boot Framework
and Controllers hidden
within Spring Boot
end note
CustomerController -> UserService : getRegisteredUser()
return registeredUser
alt registeredUser == NULL
   CustomerController -> CustomerController : createGuest()
   return guestCustomer
end
return customerData

== Shopping Cart Interaction ==
SB -> ShoppingCartController : getShoppingCart()
ShoppingCartController -> ShoppingCartController : session.getCartItems()
return cartItems
alt cart == NULL
   ShoppingCartController -> DataStore : getCachedCartItems(User)
   return cartItems
end
return cartItems

== Check Out Interaction ==
SB -> CheckOutController : checkout(customerData, shoppingCartData)
CheckOutController -> CheckOutModel : checkout(customerData, shoppingCartData)
CheckOutModel -> StripePaymentService : completePayment(Billing)
StripePaymentService -> Stripe : processPayment(Billing)
return
return
return
return model
alt model.successfulCheckOut
   SB -> CheckOutView : getSuccessfulCheckOutView()
   note right
      Exact interaction between Spring Boot Framework
       and Views (observers or pub/sub) are hidden
       within Spring Boot
    end note

return Template
else
   SB -> CheckOutView : getFailureCheckOutView()
   return Template

end

return HTTP Response
@enduml